# Generated by Django 2.2.2 on 2021-09-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstCompany',
            fields=[
                ('company_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='会社コード')),
                ('company_name', models.CharField(default='', max_length=50, verbose_name='会社名')),
                ('company_name_s', models.CharField(default='', max_length=24, verbose_name='会社名略称')),
            ],
            options={
                'verbose_name_plural': '会社登録マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstHoliday',
            fields=[
                ('holiday_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='祝日コード')),
                ('holiday_date', models.DateField(default='1900-01-01', verbose_name='日付')),
                ('holiday_name', models.CharField(default='', max_length=50, verbose_name='祝日名')),
            ],
            options={
                'verbose_name_plural': '祝日登録マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstInstitution',
            fields=[
                ('institution_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='施設コード')),
                ('institution_name', models.CharField(default='', max_length=24, verbose_name='施設名')),
                ('disp_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('institution_group_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='施設グループコード')),
                ('institution_memo', models.CharField(blank=True, max_length=2048, null=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name_plural': '施設登録マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstInstitutionGroup',
            fields=[
                ('institution_group_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='施設グループコード')),
                ('institution_group_name', models.CharField(default='', max_length=24, verbose_name='施設グループ名')),
                ('institution_group_disp_order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
                ('institution_group_memo', models.CharField(blank=True, max_length=2048, null=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name_plural': '施設グループ登録マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstScheduleType',
            fields=[
                ('schedule_type_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='予定コード')),
                ('schedule_type_name', models.CharField(default='', max_length=24, verbose_name='表示名')),
                ('sisp_order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
                ('schedule_type_color_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='予定色コード')),
            ],
            options={
                'verbose_name_plural': '予定メニュー登録マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstScheduleTypeColor',
            fields=[
                ('schedule_type_color_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='予定色コード')),
                ('schedule_type_rgb', models.CharField(default='', max_length=7, verbose_name='予定色RGBコード')),
                ('schedule_type_bg_rgb', models.CharField(default='', max_length=7, verbose_name='予定色背景RGBコード')),
                ('disp_order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
                ('schedule_type_color_discription', models.CharField(blank=True, max_length=12, null=True, verbose_name='説明')),
            ],
            options={
                'verbose_name_plural': '予定色マスタ',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleContinue',
            fields=[
                ('continue_schedule_cd', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='継続スケジュールコード')),
                ('continue_schedule_s_date', models.DateField(default='1900-01-01', verbose_name='開始日')),
                ('continue_schedule_s_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('continue_schedule_e_date', models.DateField(default='1900-01-01', verbose_name='終了日')),
                ('continue_schedule_e_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('company_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='会社コード')),
                ('schedule_type_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='予定コード')),
                ('continue_schedule_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='予定名')),
                ('institution_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='施設コード')),
                ('continue_schedule_memo', models.CharField(blank=True, max_length=2048, null=True, verbose_name='メモ')),
                ('continue_schedule_register', models.CharField(blank=True, max_length=5, null=True, verbose_name='登録者')),
                ('continue_schedule_regist_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='登録日時')),
                ('is_continue_schedule_release', models.BooleanField(blank=True, default=True, null=True, verbose_name='公開/非公開')),
            ],
            options={
                'verbose_name_plural': 'スケジュール(継続)',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleFile',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('schedule_cd', models.CharField(default='', max_length=5, verbose_name='スケジュールコード')),
                ('schedule_type', models.PositiveIntegerField(default=1, verbose_name='スケジュール種別')),
                ('schedule_file_name', models.CharField(default='', max_length=256, verbose_name='ファイル名')),
                ('schedule_file_url', models.CharField(default='', max_length=256, verbose_name='保存先')),
            ],
            options={
                'verbose_name_plural': 'スケジュールファイル',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleNormal',
            fields=[
                ('normal_schedule_cd', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='通常スケジュールコード')),
                ('normal_schedule_date', models.DateField(default='1900-01-01', verbose_name='日付')),
                ('normal_schedule_s_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('normal_schedule_e_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('company_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='会社コード')),
                ('schedule_type_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='予定コード')),
                ('normal_schedule_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='予定名')),
                ('institution_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='施設コード')),
                ('normal_schedule_memo', models.CharField(blank=True, max_length=2048, null=True, verbose_name='メモ')),
                ('normal_schedule_register', models.CharField(blank=True, max_length=5, null=True, verbose_name='登録者')),
                ('normal_schedule_regist_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='登録日時')),
                ('is_normal_schedule_release', models.BooleanField(blank=True, default=True, null=True, verbose_name='公開/非公開')),
            ],
            options={
                'verbose_name_plural': 'スケジュール(通常)',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleRepeat',
            fields=[
                ('repeat_schedule_cd', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='リピートスケジュールコード')),
                ('repeat_schedule_type', models.PositiveIntegerField(default=0, verbose_name='繰り返し条件種別')),
                ('repeat_schedule_ditail', models.PositiveIntegerField(default=0, verbose_name='繰り返し詳細1')),
                ('repeat_schedule_ditail2', models.PositiveIntegerField(default=0, verbose_name='繰り返し詳細2')),
                ('repeat_schedule_businessday', models.PositiveIntegerField(default=0, verbose_name='営業日判定')),
                ('is_repeat_limit', models.BooleanField(blank=True, default=False, null=True, verbose_name='期限有無')),
                ('repeat_limit_date', models.DateField(blank=True, default='9999-12-31', null=True, verbose_name='期限')),
                ('repeat_schedule_s_dt', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('repeat_schedule_e_dt', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('company_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='会社コード')),
                ('schedulse_type_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='予定コード')),
                ('repeat_schedule_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='予定名')),
                ('institution_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='施設コード')),
                ('repeat_schedule_memo', models.CharField(blank=True, max_length=2048, null=True, verbose_name='メモ')),
                ('repeat_schedule_register', models.CharField(blank=True, max_length=5, null=True, verbose_name='登録者')),
                ('repeat_schedule_regist_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='登録日時')),
                ('is_repeat_schedule_release', models.BooleanField(blank=True, default=True, null=True, verbose_name='公開/非公開')),
            ],
            options={
                'verbose_name_plural': 'スケジュール(リピート)',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleSpan',
            fields=[
                ('span_schedule_cd', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='期間スケジュールコード')),
                ('span_schedule_s_date', models.DateField(default='1900-01-01', verbose_name='開始日')),
                ('span_schedule_e_date', models.DateField(default='1900-01-01', verbose_name='終了日')),
                ('company_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='会社コード')),
                ('schedulse_type_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='予定コード')),
                ('span_schedule_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='予定名')),
                ('institution_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='施設コード')),
                ('span_schedule_memo', models.CharField(blank=True, max_length=2048, null=True, verbose_name='メモ')),
                ('span_schedule_register', models.CharField(blank=True, max_length=5, null=True, verbose_name='登録者')),
                ('span_schedule_regist_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='登録日時')),
                ('is_span_schedule_release', models.BooleanField(blank=True, default=True, null=True, verbose_name='公開/非公開')),
            ],
            options={
                'verbose_name_plural': 'スケジュール(期間)',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleMmemberSpan',
            fields=[
                ('schedule_member_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('account_cd', models.CharField(default='', max_length=5, verbose_name='アカウントコード')),
                ('span_schedule_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.TrnScheduleSpan')),
            ],
            options={
                'verbose_name_plural': 'スケジュール参加者(期間)',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleMmemberRepeat',
            fields=[
                ('schedule_member_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('account_cd', models.CharField(default='', max_length=5, verbose_name='アカウントコード')),
                ('repeat_schedule_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.TrnScheduleRepeat')),
            ],
            options={
                'verbose_name_plural': 'スケジュール参加者(リピート)',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleMmemberNormal',
            fields=[
                ('schedule_member_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('account_cd', models.CharField(default='', max_length=5, verbose_name='アカウントコード')),
                ('normal_schedule_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.TrnScheduleNormal')),
            ],
            options={
                'verbose_name_plural': 'スケジュール参加者(通常)',
            },
        ),
        migrations.CreateModel(
            name='TrnScheduleMmember',
            fields=[
                ('schedule_member_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('account_cd', models.CharField(default='', max_length=5, verbose_name='アカウントコード')),
                ('continue_schedule_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.TrnScheduleContinue')),
            ],
            options={
                'verbose_name_plural': 'スケジュール参加者(継続)',
            },
        ),
    ]
