# Generated by Django 2.2.2 on 2021-09-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210912_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnScheduleInstitution',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('schedule_cd', models.CharField(default='', max_length=5, verbose_name='スケジュールコード')),
                ('schedule_type', models.PositiveIntegerField(default=1, verbose_name='スケジュール種別')),
                ('institution_cd', models.CharField(blank=True, max_length=5, null=True, verbose_name='施設コード')),
            ],
            options={
                'verbose_name_plural': 'スケジュール施設',
            },
        ),
        migrations.RemoveField(
            model_name='trnschedulecontinue',
            name='institution_cd',
        ),
        migrations.RemoveField(
            model_name='trnschedulenormal',
            name='institution_cd',
        ),
        migrations.RemoveField(
            model_name='trnschedulerepeat',
            name='institution_cd',
        ),
        migrations.RemoveField(
            model_name='trnschedulespan',
            name='institution_cd',
        ),
    ]
