# Generated by Django 2.2.2 on 2021-09-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210924_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnschedulecontinue',
            name='continue_schedule_chg_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='trnschedulecontinue',
            name='continue_schedule_regist_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='trnschedulenormal',
            name='normal_schedule_chg_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='trnschedulenormal',
            name='normal_schedule_regist_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='trnschedulerepeat',
            name='repeat_schedule_chg_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='trnschedulerepeat',
            name='repeat_schedule_regist_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='trnschedulespan',
            name='span_schedule_chg_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='trnschedulespan',
            name='span_schedule_regist_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日時'),
        ),
    ]
