# Generated by Django 2.2.2 on 2021-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_trnscheduleinstitution_disp_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnschedulefile',
            name='schedule_cd',
            field=models.CharField(default='', max_length=8, verbose_name='スケジュールコード'),
        ),
        migrations.AlterField(
            model_name='trnscheduleinstitution',
            name='schedule_cd',
            field=models.CharField(default='', max_length=8, verbose_name='スケジュールコード'),
        ),
    ]
