# Generated by Django 2.2.2 on 2021-09-06 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MstAdmin',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('account_cd', models.CharField(default='', max_length=5, verbose_name='アカウントコード')),
            ],
            options={
                'verbose_name_plural': '管理者マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstBelongDepartment',
            fields=[
                ('belong_department_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('department_cd', models.CharField(default='', max_length=5, verbose_name='部署コード')),
                ('account_cd', models.CharField(default='', max_length=5, verbose_name='アカウントコード')),
                ('officer_cd', models.CharField(default='', max_length=5, verbose_name='役職コード')),
            ],
            options={
                'verbose_name_plural': '部署登録マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstBelongGroup',
            fields=[
                ('belong_group_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('group_cd', models.CharField(default='', max_length=5, verbose_name='グループコード')),
                ('account_cd', models.CharField(default='', max_length=5, verbose_name='アカウントコード')),
            ],
            options={
                'verbose_name_plural': 'グループ登録マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstDepartment',
            fields=[
                ('department_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='部署コード')),
                ('department_name', models.CharField(default='', max_length=24, verbose_name='署名')),
                ('disp_order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
            ],
            options={
                'verbose_name_plural': '部署登録マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstGroup',
            fields=[
                ('group_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='グループコード')),
                ('group_name', models.CharField(default='', max_length=24, verbose_name='グループ名')),
                ('disp_order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
            ],
            options={
                'verbose_name_plural': 'グループマスタ',
            },
        ),
        migrations.CreateModel(
            name='MstOfficer',
            fields=[
                ('officer_cd', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='役職コード')),
                ('officer_name', models.CharField(default='', max_length=24, verbose_name='役職名')),
                ('disp_order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
                ('officer_level', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='役職レベル')),
            ],
            options={
                'verbose_name_plural': '役職マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstUseFncType',
            fields=[
                ('use_func_type_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='使用機能種別コード')),
                ('use_func_type_name', models.CharField(default='', max_length=24, verbose_name='使用機能種別名')),
                ('disp_order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
                ('is_fnc_t_schedule', models.BooleanField(default=True, verbose_name='スケジュール')),
                ('is_fnc_t_file', models.BooleanField(default=False, verbose_name='ファイル管理')),
                ('is_fnc_t_timecard', models.BooleanField(default=False, verbose_name='タイムカード')),
                ('is_fnc_t_workflow', models.BooleanField(default=False, verbose_name='ワークフロー')),
                ('is_fnc_t_infoboard', models.BooleanField(default=True, verbose_name='掲示板')),
                ('is_fnc_t_message', models.BooleanField(default=True, verbose_name='メッセージ')),
                ('is_fnc_t_mail', models.BooleanField(default=False, verbose_name='メール')),
                ('is_fnc_t_task', models.BooleanField(default=True, verbose_name='タスク管理')),
                ('is_fnc_t_equipment', models.BooleanField(default=False, verbose_name='備品管理')),
                ('is_fnc_t_employee_info', models.BooleanField(default=False, verbose_name='社員情報')),
                ('is_fnc_t_employee', models.BooleanField(default=False, verbose_name='社員評価')),
            ],
            options={
                'verbose_name_plural': '使用機能種別マスタ',
            },
        ),
        migrations.CreateModel(
            name='MstAccount',
            fields=[
                ('account_cd', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='アカウントコード')),
                ('disp_name', models.CharField(default='', max_length=50, verbose_name='表示名')),
                ('use_func_type_cd', models.CharField(blank=True, default='99999', max_length=5, null=True, verbose_name='使用機能種別コード')),
                ('officer_cd', models.CharField(blank=True, default='99999', max_length=5, null=True, verbose_name='役職コード')),
                ('default_group_cd', models.CharField(blank=True, default='99999', max_length=5, null=True, verbose_name='デフォルトグループコード')),
                ('default_company_cd', models.CharField(blank=True, default='99999', max_length=5, null=True, verbose_name='デフォルト会社コード')),
                ('icon_file_url', models.ImageField(blank=True, max_length=256, null=True, upload_to=None, verbose_name='icon画像')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='作成日')),
                ('create_account', models.CharField(blank=True, max_length=5, null=True, verbose_name='作成者')),
                ('last_login_dt', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
            ],
            options={
                'verbose_name_plural': 'アカウント',
            },
        ),
    ]
