# Generated by Django 2.2.2 on 2021-09-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_mstaccount_disp_name_yomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstaccount',
            name='delete_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='失効日'),
        ),
        migrations.AddField(
            model_name='mstaccount',
            name='delete_memo',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='失効理由'),
        ),
        migrations.AddField(
            model_name='mstaccount',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='無効フラグ'),
        ),
    ]
