# Generated by Django 2.2.2 on 2021-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstProjectConfig',
            fields=[
                ('pj_config_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('pj_config_kubun_cd', models.CharField(default='', max_length=8, verbose_name='区分ID')),
                ('pj_config_key', models.CharField(default='', max_length=8, verbose_name='キー項目')),
                ('pj_config_value', models.CharField(default='', max_length=16, verbose_name='設定値')),
                ('pj_config_memo', models.CharField(default='', max_length=32, verbose_name='メモ')),
            ],
            options={
                'verbose_name_plural': 'プロジェクト設定マスタ',
            },
        ),
    ]
