# Generated by Django 2.2.2 on 2021-09-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_mstprojectconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstaccount',
            name='disp_name_yomi',
            field=models.CharField(default='', max_length=50, verbose_name='ふりがな'),
        ),
    ]
